import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "../styles/globals.css";

const lora = Lora({ subsets: ["latin"], weight: ["400", "700"], variable: "--font-lora" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`
          ${lora.variable} 
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
